<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/core.proto

namespace GPBMetadata\Proto;

class Core
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xFD\x02\x0A\x10proto/core.proto\x12\x0Cfeather.core\"&\x0A\x05Error\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\x12\x0F\x0A\x07message\x18\x02 \x01(\x09\"\x1B\x0A\x0DCorrelationId\x12\x0A\x0A\x02id\x18\x01 \x01(\x09\"#\x0A\x09Timestamp\x12\x16\x0A\x0Eunix_timestamp\x18\x01 \x01(\x03\"\$\x0A\x04Spot\x12\x0C\x0A\x04zone\x18\x01 \x01(\x09\x12\x0E\x0A\x06bucket\x18\x02 \x01(\x09\"\x1C\x0A\x08Instance\x12\x10\x0A\x08instance\x18\x01 \x01(\x09\"Q\x0A\x03Box\x12(\x0A\x08instance\x18\x01 \x01(\x0B2\x16.feather.core.Instance\x12 \x0A\x04spot\x18\x02 \x01(\x0B2\x12.feather.core.Spot\"(\x0A\x15SerializedForChunking\x12\x0F\x0A\x07content\x18\x01 \x01(\x0CB(\xAA\x02\x11Feather.Contracts\xCA\x02\x11Feather\\Contractsb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

