<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/core.proto

namespace Feather\Contracts;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>feather.core.Box</code>
 */
class Box extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.feather.core.Instance instance = 1;</code>
     */
    protected $instance = null;
    /**
     * Generated from protobuf field <code>.feather.core.Spot spot = 2;</code>
     */
    protected $spot = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Feather\Contracts\Instance $instance
     *     @type \Feather\Contracts\Spot $spot
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.feather.core.Instance instance = 1;</code>
     * @return \Feather\Contracts\Instance|null
     */
    public function getInstance()
    {
        return $this->instance;
    }

    public function hasInstance()
    {
        return isset($this->instance);
    }

    public function clearInstance()
    {
        unset($this->instance);
    }

    /**
     * Generated from protobuf field <code>.feather.core.Instance instance = 1;</code>
     * @param \Feather\Contracts\Instance $var
     * @return $this
     */
    public function setInstance(\Feather\Contracts\Instance|null $var)
    {
        $this->instance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.feather.core.Spot spot = 2;</code>
     * @return \Feather\Contracts\Spot|null
     */
    public function getSpot()
    {
        return $this->spot;
    }

    public function hasSpot()
    {
        return isset($this->spot);
    }

    public function clearSpot()
    {
        unset($this->spot);
    }

    /**
     * Generated from protobuf field <code>.feather.core.Spot spot = 2;</code>
     * @param \Feather\Contracts\Spot $var
     * @return $this
     */
    public function setSpot(\Feather\Contracts\Spot|null $var)
    {
        $this->spot = $var;

        return $this;
    }

}

