<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/core.proto

namespace Feather\Contracts;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Common message for chunking large content (e.g. user data files) in stream gRPC calls which expects the whole message for processing
 *
 * Generated from protobuf message <code>feather.core.SerializedForChunking</code>
 */
class SerializedForChunking extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes content = 1;</code>
     */
    protected $content = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $content
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes content = 1;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Generated from protobuf field <code>bytes content = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContent(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->content = $var;

        return $this;
    }

}

