<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/core.proto

namespace Feather\Contracts;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>feather.core.Timestamp</code>
 */
class Timestamp extends \Google\Protobuf\Internal\Message
{
    /**
     * Unix timestamp in milliseconds
     *
     * Generated from protobuf field <code>int64 unix_timestamp = 1;</code>
     */
    protected $unix_timestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $unix_timestamp
     *           Unix timestamp in milliseconds
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * Unix timestamp in milliseconds
     *
     * Generated from protobuf field <code>int64 unix_timestamp = 1;</code>
     * @return int|string
     */
    public function getUnixTimestamp()
    {
        return $this->unix_timestamp;
    }

    /**
     * Unix timestamp in milliseconds
     *
     * Generated from protobuf field <code>int64 unix_timestamp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUnixTimestamp(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->unix_timestamp = $var;

        return $this;
    }

}

