name: Proto Lint

on:
    #push:
    pull_request:
    schedule:
        - cron: "0 3 * * *"

jobs:
    buf-lint:
        name: "Proto files linting"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - uses: bufbuild/buf-action@v1
              with:
                  setup_only: true

            - name: Run buf lint
              run: buf lint
